// <auto-generated />
using LearnAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnAPI.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearPublished")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            Title = "Moby-Dick",
                            YearPublished = 1851
                        },
                        new
                        {
                            Id = 6,
                            Author = "KF Monkwe",
                            Title = "C# Unlocked",
                            YearPublished = 2026
                        },
                        new
                        {
                            Id = 7,
                            Author = "Robert C. Martin",
                            Title = "Clean Code",
                            YearPublished = 2008
                        },
                        new
                        {
                            Id = 8,
                            Author = "James Clear",
                            Title = "Atomic Habits",
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 9,
                            Author = "Trevor Noah",
                            Title = "Born a Crime",
                            YearPublished = 2016
                        },
                        new
                        {
                            Id = 10,
                            Author = "John Buchan",
                            Title = "The Thirty-Nine Steps",
                            YearPublished = 1915
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
